### ISSUE TITLE
CamHolderApp "Camera not found" Microsoft LifeCam Studio on macOS Catalina v10.15.4

### ISSUE THREAD

**Issue by sputn1k** [HBehrens/CamHolderApp#23]
hi, 

CamHolderApp on run gives me a error - "Camera not found" 

`Make sure to attach at least one camera of the model 'Microsoft LifeCam Studio' before running this application.`

I have a Microsoft LifeCam Studio full hd 1080p attached via usb, MacBook recognises it ok. 

MacBook Pro - macOS 10.15.4

Screengrab of MacBook system information camera - 
<img width="842" alt="Screenshot 2020-04-04 at 00 52 13" src="https://user-images.githubusercontent.com/294358/78413299-b23a3400-760e-11ea-99cd-1030a0043369.png">

**Comment by bautesta** [comment]
I am in the exact same boat, and pleased to find someone with a similar issue so recently. Have you resolved this yet? @sputn1k

**Comment by sputn1k** [comment]
@bautesta I went ahead and just paid for an App as I needed something sooner than later. (7.99) on the app store and very powerful.
